// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ListPlugins():Promise<Array<main.PluginInfo>>;

export function Ready():Promise<void>;

export function RestartPlugin(arg1:string):Promise<void>;

export function SetPluginConfig(arg1:string,arg2:Record<string, string>):Promise<void>;

export function SetPluginEnabled(arg1:string,arg2:boolean):Promise<void>;

export function StartInfo():Promise<main.startInfo>;
