// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListPlugins() {
  return window['go']['main']['App']['ListPlugins']();
}

export function Ready() {
  return window['go']['main']['App']['Ready']();
}

export function RestartPlugin(arg1) {
  return window['go']['main']['App']['RestartPlugin'](arg1);
}

export function SetPluginConfig(arg1, arg2) {
  return window['go']['main']['App']['SetPluginConfig'](arg1, arg2);
}

export function SetPluginEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetPluginEnabled'](arg1, arg2);
}

export function StartInfo() {
  return window['go']['main']['App']['StartInfo']();
}
